### ISSUE TITLE
✨ Linux support?

### ISSUE THREAD

**Issue by jd-solanki** [MatthiasGrandl/loungy#7]
Hi 👋🏻 

I loved your efforts towards this project I also wanted to build something like this but for cross-platform and mostly for linux as well. I use python mostly but python don't have great GUI framework I like so just was checking out few stuff and noticed rust implementation.

Do you have plan to add linux support?

**Comment by MatthiasGrandl** [comment]
100% I would love to add Linux support. It is still quite far out since GPUI (the UI framework) lacks cross platform support. It is however WIP and should land according to the devs before EoY. That gives me sometime to mature this project and prepare Linux support as well. Currently basic things like listing apps is built exclusively around MacOS.

**Comment by MatthiasGrandl** [comment]
The first couple of steps are done. It compiles for Linux and there is a very basic app launcher using `gtk-launch` .

It’s not very pretty yet and the GPUI linux support is in very early stages, so the window will always appear in the top left corner and there is no way to hide it yet, but to be honest I am impressed with how easy it was to even get to this point.

**Comment by sharkdp** [comment]
It works in release mode. It looks fine, but I can't interact with it (keyboard/mouse). Still shows the "Failed to read themes" message. When I try to resize the window, it crashes with

```
thread 'main' panicked at /home/shark/.cargo/git/checkouts/blade-b2bcd1de1cf7ab6a/e9d93a4/blade-graphics/src/vulkan/init.rs:721:18:
called `Result::unwrap()` on an `Err` value: ERROR_OUT_OF_DATE_KHR
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: blade_graphics::hal::init::<impl blade_graphics::hal::Context>::acquire_frame
   4: gpui::platform::blade::blade_renderer::BladeRenderer::draw
   5: <gpui::platform::linux::x11::window::X11Window as gpui::platform::PlatformWindow>::draw
   6: gpui::window::AnyWindowHandle::update
   7: util::measure
   8: gpui::window::Window::new::{{closure}}
   9: <gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::client::Client>::run
  10: gpui::app::App::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MatthiasGrandl** [comment]
@sharkdp you are on x11 right? I noticed i can only interact with it on wayland for now. For the first error you need Vulkan Validation Layer installed otherwise it crashes like this.

anyway I am in contact with the guys doing the GPUI Linux port and they are aware of all the issues. That’s mostly the reason why I did this early Linux work, so they have something other than Zed to test.

**Comment by sharkdp** [comment]
> @sharkdp you are on x11 right? I noticed i can only interact with it on wayland for now. 

yes. I see



> anyway I am in contact with the guys doing the GPUI Linux port and they are aware of all the issues. That’s mostly the reason why I did this early Linux work, so they have something other than Zed to test.

:+1:

**Comment by Partysun** [comment]
Any updates about Linux ver?

**Comment by MatthiasGrandl** [comment]
Still pretty limited. Some necessary APIs for Loungy are still not supported in Linux GPUI. For example hiding of the window.

**Comment by mikayla-maki** [comment]
> Fixed window positioning

Unfortunately, I'm sure if this is even possible on Wayland.

**Comment by Davincible** [comment]
> I am considering adding an alternative approach to hotkeys

Vouching for this one.

One extra request, can you package it as well in your flake.nix, so its easy to install on NixOS

**Comment by MatthiasGrandl** [comment]
@Davincible sadly I have 0 clue about nix. The existing flake/nix stuff if from @f8thl3ss , so maybe they are interested in adding proper nix packaging?

**Comment by f8thl3ss** [comment]
Hey! 👋
I might be able to do this. I'll have a look next week. It shouldn't be too hard to do.

**Comment by MatthiasGrandl** [comment]
> I am considering adding an alternative approach to hotkeys, so that you can instead use your system hotkey manager with loungy cli commands. I.e you bind Super+V to execute loungy clipboard, which then opens the Loungy clipboard manager.

Rough early CLI has been implemented. So you can now control Loungy via CLI:
```
Loungy is a WIP launcher in the vein of Raycast and Alfred.

Usage: loungy <Action> [Command]

Arguments:
  <Action>   [possible values: toggle, show, hide, quit, command]
  [Command]  [possible values: theme, clipboard, menu, bitwarden, tailscale, root, matrix, process]

Options:
  -h, --help     Print help
  -V, --version  Print version
```
Usage:

`loungy command clipboard`

**Comment by bbb651** [comment]
> * Fixed window positioning

The proper way to solve this on wayland would be to use [wlr-layer-shell](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) instead of [xdg-shell](https://wayland.app/protocols/xdg-shell) for the toplevel, which let's you set anchors relative to screen edges, and center it by specifying no anchors. You can also set a the layer which will place it over other toplevels, I think `top` is the correct one for a launcher. Also keep in mind you'll need to keep the normal window as a fallback for gnome because they don't support the protocol, you can instruct users to turn on `center-new-windows` with `gsettings set org.gnome.mutter center-new-windows true` (see [this issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/246)) which will at least solve the centering problem.

**Comment by MatthiasGrandl** [comment]
@bbb651 indeed I stumbled across this while evaluating switching to Iced. There is already a maintained extension for Iced to make use of wlr-layer-shell, which looks pretty easy to use.

**Comment by bbb651** [comment]
@MatthiasGrandl You might wanna look at [Gauntlet](https://github.com/project-gauntlet/gauntlet) and [cosmic-launcher](https://github.com/pop-os/cosmic-launcher) for reference and evaluation, they are both launchers based on iced with different goals and experience. The extension you're talking about is the [pop-os iced fork](https://github.com/pop-os/iced) right? They have an iced_sctk with layer-shell support (winit [doesn't support it](https://github.com/rust-windowing/winit/issues/2582)), do keep in mind they are currently rebasing from a fairly old version so I would recommend prototyping with iced master. While looking at the winit issue I found [another crate very recently created](https://github.com/waycrate/exwlshelleventloop) also for iced layer-shell, unlike the pop-os fork I've never used it myself so I can't say anything about it.

**Comment by MatthiasGrandl** [comment]
Jup I am on Iced master and yes I was talking about this https://github.com/waycrate/exwlshelleventloop . Gauntlet looks cool, didn't see that one yet!
